### ISSUE TITLE
SSE Server, Disconnection detection

### ISSUE THREAD

**Issue by federicobarera** [launchdarkly/dotnet-eventsource#10]
Hi,

this is not an issue, rather a question. Also, it's not related to the .net client. I will have to excuse in advance for not finding the right repository to ask.
The topic is related to your server side SSE technology, specifically how your server handles disconnections.

When a client close, it should terminate the TPC connection using a FIN. It's not uncommon for a client connection to drop without closing correctly the connection (this is especially true on mobile devices)
How do you handle "broken" connections on your server streaming architecture? Are you using TPC keepAlive to detect unresponsive clients?

Thanks in advance.

**Comment by arun251** [comment]
Hi @federicobarera , please send us a note at support@launchdarkly.com. Thanks!
