### ISSUE TITLE
close is not closing the stream which is leaving the socket alive

### ISSUE THREAD

**Issue by jtrahan** [launchdarkly/dotnet-eventsource#79]
I noticed that even though the cancellation token is being set the stream itself is not actually closing when cancelled which is causing the socket and the stream to stay open. To resolve the issue I made the following code changes so that it will close the stream properly.

EventSourceServices.cs  line 101
**FROM**
_using (var stream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false))_
**TO**
_await using (var stream = await response.Content.ReadAsStreamAsync(CancellationToken.None).ConfigureAwait(false))
await using (cancellationToken.Register(stream.Close)) // Calls stream.close when token has been cancelled_

<br />

and the above code then caused an exception with the StreamReader. to resolve that issue modify lines 147-151 
**FROM**
                if (line == null)
                {
                    // this means the stream is done, i.e. the connection was closed
                    return;
                }
**TO**
                if (line == null)
                {
                     reader.Dispose();  // <----- this will prevent a premature end of stream exception 
                     // this means the stream is done, i.e. the connection was closed
                    return;
                }

**Comment by jtrahan** [comment]
Actually further testing the only line that needs to be changed is line 101. await needs to be added before the using. so just the following line actually fixes both issues without additional code but I would still recommend adding the reader.Dispose() line anyway just to be sure the resources are cleared.

So again on line 101 just add await before the using
**await** using (var stream = await response.Content.ReadAsStreamAsync(CancellationToken.None).ConfigureAwait(false))

**Comment by eli-darkly** [comment]
@jtrahan We can't use the `await using` syntax because that was added in C# 8.0, and in order to support the target platforms we're currently supporting, we need to retain compatibility with C# 7.x. But thank you for pointing out this issue.

**Comment by jtrahan** [comment]
Understood. So looks like the first suggestion would be the way to go then

**Comment by jtrahan** [comment]
I switched to C# 7.3 and removed the await statements and added the Register method as listed below and this is closing the stream/socket as expected. I'm also not getting an exception on the reader but I still recommend at least adding reader?.Dispose() anyway. it wouldn't hurt anything

using (var stream = await response.Content.ReadAsStreamAsync(CancellationToken.None).ConfigureAwait(false))
using (cancellationToken.Register(stream.Close)) // Calls stream.close when token has been cancelled

**Comment by jtrahan** [comment]
My Apologies this is somehow working when I use the source code directly in my project, which is a .NET 5 project, but if I include the project as a reference from source which appears to be targeted for CORE 2.0 and .NET 4.52 then this is still not closing the stream so looks like another workaround needs to be found.

**Comment by jtrahan** [comment]
OK I found the ACTUAL issue. The code is working as expected even the one I'm getting from NuGet. I figured out that Fiddler is actually keeping the stream alive when it's capturing which is why I was getting mixed results. When Fiddler isn't capturing the stream/socket is closing as expected so I'm going to close this as not an issue.

**Comment by eli-darkly** [comment]
@jtrahan Aha. Thanks for doing the extra detective work. I wondering how adding `reader.Dispose()` could possibly have made a difference, because the `using` block would have caused `Dispose` to be called as soon as the flow left that block for any reason. I didn't think `await async` would logically have made a difference either because `stream.Dispose()` would have been called automatically and should have closed the stream just as well as `stream.DisposeAsync()` (which is what `await using` would have done). But I couldn't think what else the problem could've been, so it's a relief to know there was another cause.

**Comment by jtrahan** [comment]
Agreed that's what I kept thinking too but you never know what another developer in the framework may have done. I've seen those types of weird issues before. 

I've been using Fiddler for years now and never seen that behavior before but I've never had to utilize SSE before. The odd thing is that if I use just a normal HttpClient, which I was using before I found this project, and then close the stream fiddler then closes the stream to the server as well. so something is still kind of off somewhere in the behavior. But not enough to warrant further investigation as I can just have the .NET code just bypass fiddler all together for my purposes. 

Sorry for the fire drill

**Comment by eli-darkly** [comment]
No problem. I'm not surprised though that a proxy tool like Fiddler would have unexpected behavior for long-lasting HTTP connections using chunked transfer (which I think is likely the significant part; SSE is just a particular format of data that can be sent over such a connection). I've seen quite a few problem reports over the years from people using various proxies and other such things, where the tool didn't support streaming connections well at all, or at least not in its default configuration.
