### ISSUE TITLE
eventsource in blazor

### ISSUE THREAD

**Issue by acquleo** [launchdarkly/dotnet-eventsource#84]
I've tried open a SSE stream from a blazor client.
the call ReadAsStreamAsync on the http request don't exit creating a deadlock.

I've found that the solution is calling this extension on the http request object:
request.SetBrowserResponseStreamingEnabled(true);
which is a method extension on the Microsoft.AspNetCore.Components.WebAssembly assembly.

I believe this assembly cannot be added as reference to the source code.
A solution could be to expose a method hook from the library before execute the http request to allow the blazor code to invoke the extension method.

**Comment by eli-darkly** [comment]
(https://github.com/launchdarkly/dotnet-eventsource/pull/85 goes with this issue)

**Comment by acquleo** [comment]
the issue will be fixed. thanks
