### ISSUE TITLE
Remove dependency on Polly-Signed

### ISSUE THREAD

**Issue by ahofman** [launchdarkly/dotnet-eventsource#9]
The dependency on `Polly-Signed` has been problematic in our project, which uses `Polly` (the not-signed version). We've had to change from `Polly` to `Polly-Signed` in each of our projects, which is a bit of a hassle. 

It looks like there's just one retry policy used here; can I suggest that the retry logic be written manually and the dependency on `Polly-Signed` removed? That way this library would have less of an impact on client projects.

**Comment by arun251** [comment]
Hi @ahofman, that's a reasonable suggestion. We will work on that soon.
