### ISSUE TITLE
Error when importing because of dependencies of LaunchDarkly.Logging

### ISSUE THREAD

**Issue by Morgan-6Freedom** [launchdarkly/dotnet-eventsource#96]
<img width="549" alt="image" src="https://github.com/launchdarkly/dotnet-eventsource/assets/49686866/2d2b81c6-b84f-448f-af12-3cc17e6bee07">

Assembly 'Assets/netstandard2.0/LaunchDarkly.EventSource.dll' will not be loaded due to errors:
Unable to resolve reference 'LaunchDarkly.Logging'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.

**Comment by kinyoklion** [comment]
Hello @Morgan-6Freedom,

Is this attempting to build the event source project, or attempting to build a project you have integrated it with? If it is a project you have integrated it with, then is it possible to get some configuration information.

I do not see any similar problem when building this project, but I could see this being a problem with an ASP.Net project, most likely requiring a binding redirect.

Thanks,
Ryan

**Comment by kinyoklion** [comment]
Actually, this appears to be a Unity project. We do not officially support Unity, so I am not certain what kind of problems you may encounter.

**Comment by Morgan-6Freedom** [comment]
It worked when I imported also the logging DLL : 
<img width="244" alt="image" src="https://github.com/launchdarkly/dotnet-eventsource/assets/49686866/01168f23-eb1f-4d2e-a826-4d0bbc0fdd36">

**Comment by kinyoklion** [comment]
Yeah, the package does depend on LaunchDarkly.Logging, and it is a dependency for this project as well as also a dependency in nuget.

You can view the dependencies there as well.
https://www.nuget.org/packages/LaunchDarkly.EventSource/5.0.1#dependencies-body-tab
