### ISSUE TITLE
ASP.NET app needs binding redirect to run

### ISSUE THREAD

**Issue by exit81** [launchdarkly/dotnet-eventsource#98]
After adding LaunchDarkly.ServerSdk version 7.0.3 (which transitively pulled in LaunchDarkly.EventSource 5.0.1) to an ASP.NET MVC app targeting .NET Framework 4.7.2, requests to the app returned this error:
> Could not load file or assembly 'LaunchDarkly.Logging, Version=1.0.1.0, Culture=neutral, PublicKeyToken=d9182e4b0afd33e7' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

It seems that this is because LaunchDarkly.ServerSdk depends on LaunchDarkly.Logging 2.0.0, while LaunchDarkly.EventSource depends on LaunchDarkly.Logging 1.0.1. To resolve this, I had to add a binding redirect to the Web.config:
```
<dependentAssembly>
  <assemblyIdentity name="LaunchDarkly.Logging" publicKeyToken="d9182e4b0afd33e7" culture="neutral"/>
  <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0"/>
</dependentAssembly>
```

Is this expected behavior for this package? As far as I can tell, EventSource is the only installed package that references Logging version 1.0.1. We will be adding LaunchDarkly to more apps in the future, and it would be nice if we did not have to include a binding redirect every time.

**Comment by kinyoklion** [comment]
Hello @exit81,

Unfortunately this seems to be a peculiarity in the way that dependencies get resolved when using ASP.Net.

The LaunchDarkly.EventSource package supports a range of versions. The lowest version is 1.0.1. 

https://github.com/launchdarkly/dotnet-eventsource/blob/main/src/LaunchDarkly.EventSource/LaunchDarkly.EventSource.csproj
```
  <ItemGroup>
    <PackageReference Include="LaunchDarkly.Logging" Version="[1.0.1,3.0.0)" />
  </ItemGroup>
```

So any version greater than 1.0.1 and less than `3.0.0` will work with `LaunchDarkly.Logging`. 

This is to allow one version of the library to work with newer and older SDKs (which respectively use older and newer logging).

Other .Net targets, for instance a .Net desktop application, will automatically redirect the used logging implementation.

So, as long as our event source library remains compatible with older SDKs, we will unfortunately encounter this issue with ASP.Net.

Thank you,
Ryan

**Comment by kinyoklion** [comment]
The most recent version has the minimum set to 2.0.0 to be consistent with other packages.

Given the behavior of ASP.NET this will not eliminate the need for redirects, but it should make the default configuration not require this one for now.
